version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dogsays
      MONGO_INITDB_ROOT_PASSWORD: WoofWoof
    volumes:
            - ..\..\docker\db2\:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: dogsays
      ME_CONFIG_MONGODB_ADMINPASSWORD: WoofWoof
      ME_CONFIG_MONGODB_URL: mongodb://dogsays:WoofWoof@mongo:27017/
    depends_on:
    - mongo



  urlshortner.service:
    image: ${DOCKER_REGISTRY-}urlshortnerservice
    ports:
      - 443:443
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
    - mongo